import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Person from "../svg/icon-person.svg";
import Cog from "../svg/icon-cog.svg";
import Chart from "../svg/icon-chart.svg";
import Detail from "../components/detail";
import Story from "../components/story";
import Header from "../components/header";
import Start from "../components/start";
import Footer from "../components/footer";
import { useState } from "react";
export default function Home() {
    const [mobile, setMobile] = useState(false);
    return (
        <div
            className={`${styles.main_wrap} ${
                mobile ? styles.menu_open : null
            }`}
        >
            <Head>
                <title>
                    Frontend Mentor | myteam website challenge - Homepage
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/images/favicon-32x32.png" />
            </Head>

            <Header onMobile={() => setMobile(!mobile)} />

            <main className={styles.main}>
                <div className={styles.main_container}>
                    <div className={styles.wrap}>
                        <h1>
                            Find the best <span>talent</span>
                        </h1>
                        <div className={styles.main_info}>
                            <p>
                                Finding the right people and building high
                                performing teams can be hard. Most companies
                                aren’t tapping into the abundance of global
                                talent. We’re about to change that.
                            </p>
                        </div>
                    </div>
                </div>
            </main>

            <section className={styles.section_team} aria-label="teams">
                <div className={styles.team_container}>
                    <div className={styles.team_info}>
                        <h2>
                            Build & manage distributed teams like no one else.
                        </h2>
                    </div>
                    <div className={styles.team}>
                        <Detail
                            icon={<Person />}
                            header="Experienced Individuals"
                            paragraph="Our network is made up of highly experienced professionals who are 
                         passionate about what they do."
                        />

                        <Detail
                            icon={<Cog />}
                            header=" Easy to Implement"
                            paragraph="  Our processes have been refined over years of implementation meaning 
                            our teams always deliver."
                        />

                        <Detail
                            icon={<Chart />}
                            header="Enhanced Productivity"
                            paragraph="Our customized platform with in-built analytics helps you manage your 
                        distributed teams."
                        />
                    </div>
                </div>
            </section>
            <section className={styles.section_company} aria-label="companies">
                <div className={styles.company_container}>
                    <h2>
                        Delivering real results for top companies. Some of our
                        <span> success stories.</span>
                    </h2>
                    <div className={styles.company}>
                        <Story
                            paragraph=" “The team perfectly fit the specialized skill set required. They focused 
                        on the most essential features helping us launch the platform eight months 
                        faster than planned.”"
                            header="Kady Baker"
                            position=" Product Manager at Bookmark"
                            image={
                                <img src="/images/avatar-kady.jpg" alt="kady" />
                            }
                        />

                        <Story
                            paragraph=" “We needed to automate our entire onboarding process. The team came in and 
                            built out the whole journey. Since going live, user retention has gone 
                            through the roof!”"
                            header="Aiysha Reese"
                            position="Founder of Manage"
                            image={
                                <img
                                    src="/images/avatar-aiysha.jpg"
                                    alt="aiysha"
                                />
                            }
                        />

                        <Story
                            paragraph="“Amazing. Our team helped us build an app that delivered a new experience for 
                            hiring a physio. The launch was an instant success with 100k downloads in the 
                            first month.”"
                            header="Arthur Clarke"
                            position="Co-founder of MyPhysio"
                            image={
                                <img
                                    src="/images/avatar-arthur.jpg"
                                    alt="arthur"
                                />
                            }
                        />
                    </div>
                </div>
            </section>

            <Start />
            <Footer />
        </div>
    );
}
